export const ShowsList = [
    {
        id: 1,
        festival: 'EDC Las Vegas',
        country: 'Las Vegas, NV',
        tickets: 'https://edclasvegas.frontgatetickets.com/?utm_source=ticketmaster&utm_medium=tm_website&utm_campaign=websiteshell&utm_term=comp&utm_content=edclasvegas&irgwc=1&clickid=xsZVHM0MuxyKUQJ2oxQ%3AGQD9UkHTZmz5mwZFxc0&camefrom=CFC_BUYAT_219208&impradid=219208&REFERRAL_ID=tmfeedbuyat219208&wt.mc_id=aff_BUYAT_219208&utm_source=219208-Bandsintown&impradname=Bandsintown&utm_medium=affiliate&ircid=4272',
        day: '19',
        month: 'MAY',
        year: '2024',
    },
    {
        id: 2,
        festival: 'Amnesia Ibiza',
        country: 'Eivissa, Spain',
        tickets: 'https://store.ticketing.cm.com/elrow-amnesia-25thMay2024/step/39bd2781-0e09-4612-8e40-eb6d8c6c1c0b',
        day: '25',
        month: 'MAY',
        year: '2024',
    },
    {
        id: 3,
        festival: 'SAGA Festival',
        country: 'București, Romania',
        tickets: 'https://tickets.sagafestival.com/',
        day: '5',
        month: 'JULY',
        year: '2024',
    },
    {
        id: 4,
        festival: 'Tomorrowland',
        country: 'Boom, Belgium',
        tickets: 'https://www.tomorrowland.com/en/festival/tickets',
        day: '19',
        month: 'JUY',
        year: '2024',
    },
    {
        id: 5,
        festival: 'Barrakud Festival',
        country: 'Novalja, Croatia',
        tickets: 'https://www.barrakud.com/tickets/',
        day: '13',
        month: 'AUGUST',
        year: '2024',
    },
    {
        id: 6,
        festival: 'ARC Music Fesitval',
        country: 'Chicago, IL',
        tickets: 'https://arcmusicfestival.frontgatetickets.com/?utm_source=ticketmaster&utm_medium=tm_website&utm_campaign=websiteshell&utm_term=comp&utm_content=arcmusicfestival&irgwc=1&clickid=xsZVHM0MuxyKUQJ2oxQ%3AGQD9UkHTZ8WRmwZFxc0&camefrom=CFC_BUYAT_219208&impradid=219208&REFERRAL_ID=tmfeedbuyat219208&wt.mc_id=aff_BUYAT_219208&utm_source=219208-Bandsintown&impradname=Bandsintown&utm_medium=affiliate&ircid=4272',
        day: '30',
        month: 'AUGUST',
        year: '2024',
    },
]